### ISSUE TITLE
Can you put out a detailed tutorial for changing/updating the portfolio

### ISSUE THREAD

**Issue by zac11** [salomonelli/personal-portfolio#1]
Hi,

Can you update the readme file with more details about how to change the contents of the files and how did you manage to host it on github? 

I have been trying a few things but haven't been able to achieve quite a lot frankly, due to my limited knowledge of React. It would be highly appreciable if you can update the readme with a tutorial of sorts.

Thanks 👍

**Comment by salomonelli** [comment]
Hi @zac11 , thanks for the hint! I'll try to get to this as soon as possible.
