### ISSUE TITLE
Add Licence

### ISSUE THREAD

**Issue by stefanjudis** [salomonelli/personal-portfolio#2]
Hello Sara,

i found you're project and would like to use it in a talk I'll give tomorrow.
Do you mind me asking what the copyrights are?

A `LICENCE` file would be nice. :) 

Thanks a lot for putting it on GitHub. 👏🏻

**Comment by salomonelli** [comment]
Hi Stefan, 

there is a LICENCE.md file in the root directory (MIT Licence) 😊

Do you mind telling me what your talk is about (hopefully not about samples of bad coding practices 😁)? We can converse via twitter or something if you like

**Comment by stefanjudis** [comment]
Oh well... I don't know what was wrong with today. :D Sorry about the noise. :\

> Do you mind telling me what your talk is about (hopefully not about samples of bad coding practices 😁)? We can converse via twitter or something if you like

I was looking for portfolio sites that I could quickly equip with a CMS to make the data editable. :)
(disclaimer I work for contentful).

Your site looks nice btw! Like it a lot. 👍🏻
